---
version: '2'
services:
  guiguts:
    image: tangledhelix/guiguts:1.2.3-4
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ~/dp/pp:/dp/pp
      - ~/.guiguts/header.txt:/dp/guiguts/src/header.txt
      - ~/.guiguts/setting.rc:/dp/guiguts/src/setting.rc
