---
version: '2'
services:
  guiguts:
    image: tangledhelix/guiguts:latest
    build: ./guiguts
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ~/dp/pp:/dp/pp
      - ~/dp/guiguts/header.txt:/dp/guiguts/header.txt
      - ~/dp/guiguts/setting.rc:/dp/guiguts/setting.rc
